# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: VS Code中文社区
subtitle: ''
description: ''
keywords:
author: VSCodeCC
language: zh-CN
timezone: ''

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'tomorrow'
  line_number: false    # default false
  custom_css:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hexo-theme-matery
theme_config:
  # The configuration of the second button in the home banner,
  # including the display name of the button, the font awesome icon, and the hyperlink to the button.
  # 首页 banner 中的第二个按钮的配置，包括按钮的显示名称、font awesome图标和按钮的超链接.
  indexbtn:
    enable: true
    name: Github
    icon: fab fa-github-alt
    url: https://github.com/vscodecc/vscodecc
  # Whether to display fork me on github icon and link, default true, You can change it to your repo address
  # 配置是否在 header 中显示 fork me on github 的图标，默认为true，你可以修改为你的仓库地址.
  githubLink:
    enable: true
    url: https://github.com/vscodecc/vscodecc.github.io
    title: Fork Me
  # The configurations of the second line of home banner
  # icon/button will not show up if you leave the corresponding socialLink empty
  # 首页 banner 中的第二行个人信息配置，留空即不启用
  socialLink:
    github:  https://github.com/vscodecc
    email: # 1181062873@qq.com
    facebook: # https://www.facebook.com/xxx
    twitter: # https://twitter.com/xxx
    qq: # 1181062873
    weibo: # https://weibo.com/xxx
    zhihu: # https://www.zhihu.com/xxx
    rss: true # true、false

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: ''
